apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pipeline-sample
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-pipeline-sample
  template:
    metadata:
      labels:
        app: go-pipeline-sample
    spec:
      containers:
      - image: teshapp
        name: go-pipeline-sample
        ports:
        - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pipeline-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-pipeline-sample
  template:
    metadata:
      labels:
        app: go-pipeline-sample
    spec:
      containers:
      - name: go-pipeline-sample
        image: hiteshreeruparell/teshapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  selector:
    app: go-pipeline-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
