apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pipeline-sample
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-pipeline-samplei
  template:
    metadata:
      labels:
        app: go-pipeline-sample
    spec:
      containers:
      - image: hiteshreeruparell/demo:goapp
        name: go-pipeline-sample
        ports:
        - containerPort: 80
