apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pipeline-sample
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-pipeline-sample
  template:
    metadata:
      labels:
        app: go-pipeline-sample
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: go-pipeline-sample
        ports:
        - containerPort: 80
