pipeline:
  identifier: Build_go_pipeline_sample_1723732123505
  name: Build go-pipeline-sample
  orgIdentifier: default
  projectIdentifier: guestbook
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: <+input>
                    repo: hiteshreeruparell/demo
                    tags:
                      - goapp
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
